In [2]:
import mlflow
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT}/mlflow.db")

run_id = "1e39c7273c574f5ab31baee3b7325f9f"

mlflow.register_model(
    model_uri=f"runs:/{run_id}/model",
    name="rul-predictor"
)

Successfully registered model 'rul-predictor'.
2026/04/23 14:15:07 WARNING mlflow.tracking._model_registry.fluent: Run with id 1e39c7273c574f5ab31baee3b7325f9f has no artifacts at artifact path 'model', registering model based on models:/m-3a17dee96f9a4096ba00711be30067b0 instead
Created version '1' of model 'rul-predictor'.

<ModelVersion: aliases=[], creation_timestamp=1776946507285, current_stage='None', deployment_job_state=None, description=None, last_updated_timestamp=1776946507285, metrics=None, model_id=None, name='rul-predictor', params=None, run_id='1e39c7273c574f5ab31baee3b7325f9f', run_link=None, source='models:/m-3a17dee96f9a4096ba00711be30067b0', status='READY', status_message=None, tags={}, user_id=None, version=1, workspace='default'>

In [4]:
from mlflow.tracking import MlflowClient

client = MlflowClient()
client.transition_model_version_stage(
    name="rul-predictor",
    version=1,
    stage="Production"
)

C:\Users\wasse\AppData\Local\Temp\ipykernel_27412\975453417.py:4: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

<ModelVersion: aliases=[], creation_timestamp=1776946507285, current_stage='Production', deployment_job_state=None, description=None, last_updated_timestamp=1776946909415, metrics=None, model_id=None, name='rul-predictor', params=None, run_id='1e39c7273c574f5ab31baee3b7325f9f', run_link=None, source='models:/m-3a17dee96f9a4096ba00711be30067b0', status='READY', status_message=None, tags={}, user_id=None, version=1, workspace='default'>

In [24]:
import pandas as pd
import sys
import os

# add parent directory to import path
current = os.getcwd()
parent = os.path.dirname(current)
sys.path.append(parent)


df = pd.read_csv(parent+"/data/raw/test_FD001.txt", delim_whitespace=True, names=["unit number", "time, in cycles","operational setting 1","operational setting 2","operational setting 3","sensor measurement  1",
                                                                                            "sensor measurement  2","sensor measurement  3", "sensor measurement  4","sensor measurement  5",
                                                                                            "sensor measurement  6","sensor measurement  7","sensor measurement  8","sensor measurement  9",
                                                                                            "sensor measurement  10","sensor measurement  11", "sensor measurement  12","sensor measurement  13",
                                                                                            "sensor measurement  14","sensor measurement  15", "sensor measurement  16","sensor measurement  17",
                                                                                            "sensor measurement  18","sensor measurement  19", "sensor measurement  20","sensor measurement  21"])
df.head()

C:\Users\wasse\AppData\Local\Temp\ipykernel_23684\2612749113.py:11: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(parent+"/data/raw/test_FD001.txt", delim_whitespace=True, names=["unit number", "time, in cycles","operational setting 1","operational setting 2","operational setting 3","sensor measurement  1",

,unit number,"time, in cycles",operational setting 1,operational setting 2,operational setting 3,sensor measurement 1,sensor measurement 2,sensor measurement 3,sensor measurement 4,sensor measurement 5,...,sensor measurement 12,sensor measurement 13,sensor measurement 14,sensor measurement 15,sensor measurement 16,sensor measurement 17,sensor measurement 18,sensor measurement 19,sensor measurement 20,sensor measurement 21
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,521.72,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,522.16,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,521.97,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,521.38,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,522.15,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130

In [ ]:
from src.features.feature_engineering import FeatureEngineer
import mlflow
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT}/mlflow.db")


fe = FeatureEngineer.load(PROJECT_ROOT / "artifacts" / f"feature_engineer_{feature_length}.joblib")
df_smoothed = fe.transform(df)

In [3]:
df_smoothed

,unit number,"time, in cycles",operational setting 1,operational setting 2,operational setting 3,sensor measurement 2_mean,sensor measurement 2_std,sensor measurement 2_diff,sensor measurement 3_mean,sensor measurement 3_std,...,sensor measurement 15_diff,sensor measurement 17_mean,sensor measurement 17_std,sensor measurement 17_diff,sensor measurement 20_mean,sensor measurement 20_std,sensor measurement 20_diff,sensor measurement 21_mean,sensor measurement 21_std,sensor measurement 21_diff
29,1,30,-0.0025,0.0004,100.0,642.310333,0.300522,0.84,1585.795333,3.650772,...,-0.0102,391.700000,0.876907,-1.0,38.983667,0.094850,0.07,23.379893,0.035165,0.0448
30,1,31,-0.0006,0.0004,100.0,642.295667,0.274285,-0.21,1585.659667,3.744615,...,-0.0086,391.733333,0.907187,2.0,38.982000,0.097500,-0.28,23.379283,0.035437,-0.0517
60,2,30,0.0015,0.0004,100.0,642.537333,0.268302,0.32,1589.019667,5.077375,...,0.0282,392.633333,0.764890,-1.0,38.859667,0.092195,-0.07,23.325907,0.070870,0.0013
61,2,31,0.0003,0.0002,100.0,642.541000,0.270776,0.02,1589.087000,5.094586,...,-0.0317,392.700000,0.794377,1.0,38.851000,0.090757,-0.19,23.323047,0.069822,0.0017
62,2,32,0.0032,0.0002,100.0,642.550000,0.274176,0.01,1589.283000,5.180817,...,-0.0251,392.733333,0.827682,0.0,38.847667,0.092984,0.00,23.323837,0.069571,0.0074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,642.764000,0.323724,0.14,1592.622000,3.637274,...,0.0286,393.600000,1.037238,-1.0,38.806000,0.123081,0.02,23.287270,0.065216,-0.0978
13092,100,195,-0.0011,-0.0001,100.0,642.775000,0.333609,-0.02,1592.672667,3.670020,...,-0.0203,393.666667,1.061337,1.0,38.803000,0.127770,-0.08,23.288940,0.064254,0.0797
13093,100,196,-0.0006,-0.0003,100.0,642.810000,0.346649,0.22,1592.692667,3.670963,...,0.0057,393.733333,1.080655,0.0,38.796000,0.131925,0.05,23.284170,0.065010,-0.0720
13094,100,197,-0.0038,0.0001,100.0,642.830000,0.354906,-0.18,1592.832667,3.675984,...,0.0142,393.733333,1.080655,0.0,38.787000,0.131678,0.04,23.281540,0.063892,0.0648
13095,100,198,0.0013,0.0003,100.0,642.830333,0.355018,-0.31,1593.381333,3.719423,...,0.0192,393.833333,1.147211,1.0,38.778000,0.127912,0.04,23.276977,0.065735,-0.0844

In [4]:
df = df_smoothed.sort_values(["unit number", "time, in cycles"])
df_last30 = df.groupby("unit number").tail(30)
df_last30

,unit number,"time, in cycles",operational setting 1,operational setting 2,operational setting 3,sensor measurement 2_mean,sensor measurement 2_std,sensor measurement 2_diff,sensor measurement 3_mean,sensor measurement 3_std,...,sensor measurement 15_diff,sensor measurement 17_mean,sensor measurement 17_std,sensor measurement 17_diff,sensor measurement 20_mean,sensor measurement 20_std,sensor measurement 20_diff,sensor measurement 21_mean,sensor measurement 21_std,sensor measurement 21_diff
29,1,30,-0.0025,0.0004,100.0,642.310333,0.300522,0.84,1585.795333,3.650772,...,-0.0102,391.700000,0.876907,-1.0,38.983667,0.094850,0.07,23.379893,0.035165,0.0448
30,1,31,-0.0006,0.0004,100.0,642.295667,0.274285,-0.21,1585.659667,3.744615,...,-0.0086,391.733333,0.907187,2.0,38.982000,0.097500,-0.28,23.379283,0.035437,-0.0517
60,2,30,0.0015,0.0004,100.0,642.537333,0.268302,0.32,1589.019667,5.077375,...,0.0282,392.633333,0.764890,-1.0,38.859667,0.092195,-0.07,23.325907,0.070870,0.0013
61,2,31,0.0003,0.0002,100.0,642.541000,0.270776,0.02,1589.087000,5.094586,...,-0.0317,392.700000,0.794377,1.0,38.851000,0.090757,-0.19,23.323047,0.069822,0.0017
62,2,32,0.0032,0.0002,100.0,642.550000,0.274176,0.01,1589.283000,5.180817,...,-0.0251,392.733333,0.827682,0.0,38.847667,0.092984,0.00,23.323837,0.069571,0.0074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,642.764000,0.323724,0.14,1592.622000,3.637274,...,0.0286,393.600000,1.037238,-1.0,38.806000,0.123081,0.02,23.287270,0.065216,-0.0978
13092,100,195,-0.0011,-0.0001,100.0,642.775000,0.333609,-0.02,1592.672667,3.670020,...,-0.0203,393.666667,1.061337,1.0,38.803000,0.127770,-0.08,23.288940,0.064254,0.0797
13093,100,196,-0.0006,-0.0003,100.0,642.810000,0.346649,0.22,1592.692667,3.670963,...,0.0057,393.733333,1.080655,0.0,38.796000,0.131925,0.05,23.284170,0.065010,-0.0720
13094,100,197,-0.0038,0.0001,100.0,642.830000,0.354906,-0.18,1592.832667,3.675984,...,0.0142,393.733333,1.080655,0.0,38.787000,0.131678,0.04,23.281540,0.063892,0.0648
13095,100,198,0.0013,0.0003,100.0,642.830333,0.355018,-0.31,1593.381333,3.719423,...,0.0192,393.833333,1.147211,1.0,38.778000,0.127912,0.04,23.276977,0.065735,-0.0844

In [ ]:
import numpy as np

def get_last_window(df_smoothed, feature_cols, window_length=30):
    X_list = []
    
    for unit_id, group in df_smoothed.groupby("unit number"):
        data = group[feature_cols].to_numpy()
        
        if len(data) >= window_length:
            window = data[-window_length:]
        else:
            # pad at the beginning by repeating first row
            pad_size = window_length - len(data)
            padding = np.repeat(data[[0]], pad_size, axis=0)
            window = np.vstack([padding, data])
        
        X_list.append(window)
    
    return np.array(X_list)

feature_cols = [col for col in df_smoothed.columns if col not in ["unit number", "time, in cycles", "RUL"]]
X_test = get_last_window(df_smoothed, feature_cols, window_length=30)
X_test.shape

(100, 30, 45)

In [6]:
df_smoothed.groupby("unit number").size().min()

np.int64(12)

In [16]:
df_smoothed["unit number"].nunique()

100

In [19]:
df.groupby("unit number").size().min()

np.int64(31)

In [26]:
import duckdb
import pandas as pd
import sys
import os


# add parent directory to import path
current = os.getcwd()
parent = os.path.dirname(current)
sys.path.append(parent)


con = duckdb.connect(parent + "/database/cmapss.db")
con.execute("CREATE TABLE IF NOT EXISTS features_25_fd001_test AS SELECT * FROM df_smoothed")


# query → pandas dataframe in one line
df_test = con.execute("SELECT * FROM features_25_fd001_test").df()

# or with filtering
#df_filtered = con.execute("SELECT * FROM features_20_fd001 WHERE RUL < 50").df()

con.close()

In [18]:
y_test = pd.read_csv(parent+"/data/raw/RUL_FD001.txt", header=None).values.flatten()

In [19]:
y_test

array([112,  98,  69,  82,  91,  93,  91,  95, 111,  96,  97, 124,  95,
       107,  83,  84,  50,  28,  87,  16,  57, 111, 113,  20, 145, 119,
        66,  97,  90, 115,   8,  48, 106,   7,  11,  19,  21,  50, 142,
        28,  18,  10,  59, 109, 114,  47, 135,  92,  21,  79, 114,  29,
        26,  97, 137,  15, 103,  37, 114, 100,  21,  54,  72,  28, 128,
        14,  77,   8, 121,  94, 118,  50, 131, 126, 113,  10,  34, 107,
        63,  90,   8,   9, 137,  58, 118,  89, 116, 115, 136,  28,  38,
        20,  85,  55, 128, 137,  82,  59, 117,  20])

In [ ]:
import mlflow
mlflow.register_model("runs:/2015dd2c611b498d9d4128d1f54e2b63/model", "rul-predictor")

Registered model 'rul-predictor' already exists. Creating a new version of this model...
2026/04/23 16:45:24 WARNING mlflow.tracking._model_registry.fluent: Run with id 2015dd2c611b498d9d4128d1f54e2b63 has no artifacts at artifact path 'model', registering model based on models:/m-285cbd231faa48db9871fe5f473d7451 instead
Created version '2' of model 'rul-predictor'.

<ModelVersion: aliases=[], creation_timestamp=1776955524018, current_stage='None', deployment_job_state=None, description=None, last_updated_timestamp=1776955524018, metrics=None, model_id=None, name='rul-predictor', params=None, run_id='2015dd2c611b498d9d4128d1f54e2b63', run_link=None, source='models:/m-285cbd231faa48db9871fe5f473d7451', status='READY', status_message=None, tags={}, user_id=None, version=2, workspace='default'>

In [28]:
X_test.shape

(100, 30, 45)

In [36]:
for feature in test_input["sensor_readings"]:
    if len(feature) != 45:
        raise ValueError(f"Each feature list must have length {45}, but got {len(feature)}")

In [35]:
len(test_input["sensor_readings"][0])

45

In [37]:
import numpy as np
import json

# take a real window from your test set
test_input = {"sensor_readings": X_test[0].tolist()}
print(json.dumps(test_input))

{"sensor_readings": [[-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.286819655575219, 1.6599999999998545, 8.416446666666667, 0.020799813217552428, -0.010200000000001097, 391.7, 0.8769067893689553, -1.0, 38.983666666666664, 0.0948495481360316, 0.07000000000000028, 23.37989333333333, 0.035165087832946536, 0.04479999999999862], [-0.0025, 0.0004, 100.0, 642.3103333333333, 0.3005223421992387, 0.8399999999999181, 1585.7953333333332, 3.650771985752331, -1.4300000000000637, 1401.6133333333335, 3.927677503908958, 2.8600000000001273, 554.1356666666667, 0.42885318871529127, -0.049999999999954525, 2388.046333333333, 0.030567430642559297, 0.010000000000218279, 9048.809666666666, 4.202588269259498, 1.3400000000001455, 47.31133333333333, 0.10334853429163705, -0.020000000000003126, 521.9793333333333, 0.2531856798986524, -0.6100000000000136, 2388.0566666666664, 0.028567323186033618, 0.02999999999974534, 8131.034, 3.28681